name: Build & Publish Release APK

on:
  push:
    branches:
      - main

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Make Gradle executable
      run: chmod +x ./gradlew
      
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: version
      run: echo "version=$(grep -o -E 'versionName = \"[[:digit:]\.]+\"' app/build.gradle.kts | grep -o -E '[[:digit:]\.]+')" >> $GITHUB_OUTPUT
      
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.version }}
        files: |
          app/build/outputs/apk/release/app-release-unsigned.apk
