name: Build Docs

on:
  push:
    branches:
      - main
    paths:
      - 'fastlane/**/*'
      - 'scripts/generate-readme.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Readme
        run:  bash ${GITHUB_WORKSPACE}/scripts/generate-readme.sh

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions'
