name: Build Docs

on:
  push:
    branches:
      - main
    paths:
      - 'fastlane/**/*'
      - 'scripts/generate-readme.sh'
      - '.github/workflows/docs.yml'

jobs:
  build:
    permissions:
      id-token: write # Enable OIDC
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Generate Readme
        run:  bash ${GITHUB_WORKSPACE}/scripts/generate-readme.sh

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Sign commit and push changes
        run: |
          git add .
          git commit -S -m "Generated docs"
          git push
