name: Build Docs

on:
  push:
    branches:
      - main
    paths:
      - 'fastlane/**/*'
      - 'scripts/generate-readme.sh'
      - '.github/workflows/docs.yml'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Generate Readme
        run:  bash ${GITHUB_WORKSPACE}/scripts/generate-readme.sh

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated docs"
          git push --force
