name: Build Docs

on:
  push:
    branches:
      - main
    paths:
      - 'fastlane/**/*'
      - 'scripts/generate-readme.sh'
      - '.github/workflows/docs.yml'

jobs:
  build:
    permissions:
      id-token: write # Enable OIDC
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: chainguard-dev/actions/setup-gitsign@main

      - name: Generate Readme
        run:  bash ${GITHUB_WORKSPACE}/scripts/generate-readme.sh

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -S --message="Overwritten by Github Actions"
          git push
